---
apiVersion: v1
kind: Service
metadata:
  name: jwt-vending-service
  labels:
    app: jwt-vending-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: jwt-vending-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-vending-service
  labels:
    app: jwt-vending-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-vending-service
  template:
    metadata:
      labels:
        app: jwt-vending-service
      annotations:
        # Disable Consul Connect injection for infrastructure services
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      containers:
        - name: jwt-vending-service
          image: gcr.io/PROJECT_ID/jwt-vending-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"