---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: service-b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-b-wasm-filter
data:
  # Server WASM filter configuration for Envoy
  # This will be mounted and referenced by Consul Connect
  filter.wasm: |
    # Binary WASM module will be stored here via build process
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
      annotations:
        # Enable Consul Connect injection with sidecar proxy
        "consul.hashicorp.com/connect-inject": "true"
        # Configure Envoy to use our server WASM filter
        "consul.hashicorp.com/envoy-extra-args": "--log-level debug"
    spec:
      serviceAccountName: service-b
      containers:
        - name: service-b
          image: gcr.io/PROJECT_ID/service-b:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: SERVICE_ID
              value: "service-b"
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b